# docker-compose.yml
version: '3.8'

services:
  frontend:
    build:
      context: ./apps/collabydraw
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - websocket
      - database

  websocket:
    build:
      context: ./apps/ws
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    depends_on:
      - database

  database:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: collabydraw
      POSTGRES_PASSWORD: your_secure_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data: